# Generated by Django 3.0.4 on 2020-03-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.SlugField(max_length=64)),
                ('api_key', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
