# Generated by Django 3.0.4 on 2020-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_apikeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='key_name',
            field=models.TextField(max_length=64),
        ),
    ]
