# Generated by Django 3.0.4 on 2020-04-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_apikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throttling',
            fields=[
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest_api.ApiKeys')),
                ('date', models.DateField(auto_now=True)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apikeys',
            options={'verbose_name_plural': 'Api Keys'},
        ),
    ]
