# Generated by Django 3.0.4 on 2020-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_throttling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='day_limit',
            field=models.IntegerField(),
        ),
    ]
