# Generated by Django 3.0.5 on 2020-04-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_apikeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='code_name',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
